In [7]:
from gwsnr.ripple import RippleInnerProduct
import numpy as np

ripple = RippleInnerProduct()

In [4]:
m1_msun = 20.0 # In solar masses
m2_msun = 19.0
chi1 = 0.5 # Dimensionless spin
chi2 = -0.5
tc = 0.0 # Time of coalescence in seconds
phic = 0.0 # Time of coalescence
dist_mpc = 440 # Distance to source in Mpc
inclination = 0.0 # Inclination Angle

# The PhenomD waveform model is parameterized with the chirp mass and symmetric mass ratio
from ripple import ms_to_Mc_eta
import jax.numpy as jnp
Mc, eta = ms_to_Mc_eta(jnp.array([m1_msun, m2_msun]))
theta_ripple = jnp.array([Mc, eta, chi1, chi2, dist_mpc, tc, phic, inclination])
# Now we need to generate the frequency grid
f_l = 20.
f_u = 512.
del_f = 1./4.
fs = jnp.arange(f_l, f_u, del_f)
f_ref = f_l

# And finally lets generate the waveform!
ripple.vmap_waveform(np.array([fs]), np.array([theta_ripple]), np.array([f_ref]))

(Array([[ 5.3941103e-23+0.0000000e+00j,
         -5.1535889e-23+1.2927841e-23j,
          4.3517569e-23-2.9090902e-23j, ...,
          4.2845521e-25+4.2995715e-25j,
          4.2638114e-25+4.2768000e-25j,
          4.2431487e-25+4.2541267e-25j]], dtype=complex64),
 Array([[ 0.0000000e+00-5.3941103e-23j,
          1.2927841e-23+5.1535889e-23j,
         -2.9090902e-23-4.3517569e-23j, ...,
          4.2995715e-25-4.2845521e-25j,
          4.2768000e-25-4.2638114e-25j,
          4.2541267e-25-4.2431487e-25j]], dtype=complex64))

In [ ]:
m1_msun = 20.0 # In solar masses
m2_msun = 19.0
chi1 = 0.5 # Dimensionless spin
chi2 = -0.5
tc = 0.0 # Time of coalescence in seconds
phic = 0.0 # Time of coalescence
dist_mpc = 440 # Distance to source in Mpc
inclination = 0.0 # Inclination Angle

gw_param_dict = {
    'mass_1': np.array([m1_msun]),
    'mass_2': np.array([m2_msun]),
    'a_1': np.array([chi1]),
    'a_2': np.array([chi2]),
    'luminosity_distance': np.array([dist_mpc]),
    'geocent_time': np.array([tc]),
    'phase': np.array([phic]),
    'theta_jn': np.array([inclination])
}
ripple.noise_weighted_inner_product_jax(
    gw_param_dict=gw_param_dict,
    psd_list=gwsnr.psds_list,
    detector_list=gwsnr.detector_list,
)

AttributeError: 'RippleInnerProduct' object has no attribute 'psds_list'

In [20]:
gwsnr.compute_bilby_snr(gw_param_dict=gw_param_dict)

100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.20it/s]


{'L1': array([49.67374168]),
 'H1': array([41.95579152]),
 'V1': array([24.73387519]),
 'optimal_snr_net': array([69.56675669])}

In [9]:
from gwsnr import GWSNR
import numpy as np

gwsnr = GWSNR(
        npool=4,
        sampling_frequency=2048.0,
        waveform_approximant="IMRPhenomD",
        minimum_frequency=20.0,
        snr_type="inner_product_jax",
        interpolator_dir="./interpolator_pickle",
        create_new_interpolator=False,
        gwsnr_verbose=False,
        multiprocessing_verbose=True,
        mtot_cut=True,
    )

m1_msun = 20.0 # In solar masses
m2_msun = 19.0
chi1 = 0.5 # Dimensionless spin
chi2 = -0.5
tc = 0.0 # Time of coalescence in seconds
phic = 0.0 # Time of coalescence
dist_mpc = 440 # Distance to source in Mpc
inclination = 0.0 # Inclination Angle
gw_param_dict = {
    'mass_1': np.array([m1_msun]),
    'mass_2': np.array([m2_msun]),
    'a_1': np.array([chi1]),
    'a_2': np.array([chi2]),
    'luminosity_distance': np.array([dist_mpc]),
    'geocent_time': np.array([tc]),
    'phase': np.array([phic]),
    'theta_jn': np.array([inclination])
}
gwsnr.snr(gw_param_dict=gw_param_dict)


Initializing GWSNR class...

psds not given. Choosing bilby's default psds


solving SNR with inner product JAX
theta_ripple : [[ 1.6969042e+01  2.4983564e-01  5.0000000e-01 -5.0000000e-01
   4.4000000e+02  0.0000000e+00  0.0000000e+00  0.0000000e+00]]


/Users/phurailatpamhemantakumar/anaconda3/envs/gwsnr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.81it/s]


{'L1': array([49.67369594]),
 'H1': array([41.95575289]),
 'V1': array([24.73385048]),
 'optimal_snr_net': array([69.56669195])}

In [12]:
gwsnr.snr(mass_1=np.array([20.]), mass_2=np.array([19.]), a_1=np.array([0.5]), a_2=np.array([-0.5]), luminosity_distance=np.array([440.]), geocent_time=np.array([0.0]), phase=np.array([0.0]), theta_jn=np.array([0.0]))

solving SNR with inner product JAX
fs : [[0.00000000e+00 2.00000003e-01 4.00000006e-01 ...
  1.02360004e+03 1.02379999e+03 1.02400000e+03]]
theta_ripple : [[ 1.6969042e+01  2.4983564e-01  5.0000000e-01 -5.0000000e-01
   4.4000000e+02  0.0000000e+00  0.0000000e+00  0.0000000e+00]]
hp : [[            nan           +nanj
   9.31166505e-21-7.96913153e-21j
   3.02415293e-21-4.53789749e-21j ...
  -6.08449357e-29+5.98742430e-29j
  -6.07023929e-29+5.96847676e-29j
  -6.05610717e-29+5.94949431e-29j]]
hc : [[            nan           +nanj
  -7.96913153e-21-9.31166505e-21j
  -4.53789749e-21-3.02415293e-21j ...
   5.98742430e-29+6.08449357e-29j
   5.96847676e-29+6.07023929e-29j
   5.94949431e-29+6.05610717e-29j]]


/Users/phurailatpamhemantakumar/anaconda3/envs/gwsnr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.72it/s]


{'L1': array([49.67369594]),
 'H1': array([41.95575289]),
 'V1': array([24.73385048]),
 'optimal_snr_net': array([69.56669195])}

In [8]:
theta_ripple

Array([ 1.7411015e+01,  2.5000000e-01,  5.0000000e-01,
       -5.0000000e-01,  4.4000000e+02,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00], dtype=float32)

In [13]:
import jax.numpy as jnp

from ripple.waveforms import IMRPhenomXAS
from ripple import ms_to_Mc_eta
# Get a frequency domain waveform
# source parameters

m1_msun = 20.0 # In solar masses
m2_msun = 19.0
chi1 = 0.5 # Dimensionless spin
chi2 = -0.5
tc = 0.0 # Time of coalescence in seconds
phic = 0.0 # Time of coalescence
dist_mpc = 440 # Distance to source in Mpc
inclination = 0.0 # Inclination Angle

# The PhenomD waveform model is parameterized with the chirp mass and symmetric mass ratio
Mc, eta = ms_to_Mc_eta(jnp.array([m1_msun, m2_msun]))

# These are the parametrs that go into the waveform generator
# Note that JAX does not give index errors, so if you pass in the
# the wrong array it will behave strangely
theta_ripple = jnp.array([Mc, eta, chi1, chi2, dist_mpc, tc, phic, inclination])

# Now we need to generate the frequency grid
f_l = 20
f_u = 1024
del_f = 1/4.
fs = jnp.arange(f_l, f_u, del_f)
f_ref = f_l

# And finally lets generate the waveform!
IMRPhenomXAS.gen_IMRPhenomXAS_hphc(fs, theta_ripple, f_ref)


(Array([-3.8084434e-23-3.8084396e-23j,
         4.5623206e-23+2.7072990e-23j,
        -5.1343526e-23-9.7666944e-24j, ...,
        -7.4017911e-29-8.4835023e-31j,
        -7.3761390e-29-7.0301747e-31j,
        -7.3505452e-29-5.5868472e-31j], dtype=complex64),
 Array([-3.8084396e-23+3.8084434e-23j,
         2.7072990e-23-4.5623206e-23j,
        -9.7666944e-24+5.1343526e-23j, ...,
        -8.4835023e-31+7.4017911e-29j,
        -7.0301747e-31+7.3761390e-29j,
        -5.5868472e-31+7.3505452e-29j], dtype=complex64))

In [2]:
import numpy as np
import pytest
import time
from gwsnr import GWSNR
from gwsnr.utils import append_json

np.random.seed(1234)

class TestGWSNRInnerProduct:
    """
    Test suite for GWSNR inner product-based SNR calculations.
    
    Validates exact SNR computation using direct waveform generation and noise-weighted
    inner products. Tests core functionality, waveform compatibility, detector flexibility,
    and performance characteristics of the `snr_type="inner_product"` method.
    """
    
    def _generate_bbh_params(self, nsamples, include_spins=False, distance=500.0):
        """Generate realistic BBH parameters for testing."""
        mtot = np.random.uniform(20, 200, nsamples)
        mass_ratio = np.random.uniform(0.2, 1, nsamples)
        
        params = {
            'mass_1': mtot / (1 + mass_ratio),
            'mass_2': mtot * mass_ratio / (1 + mass_ratio),
            'luminosity_distance': distance * np.ones(nsamples),
            'geocent_time': 1246527224.169434 * np.ones(nsamples),
            'theta_jn': np.random.uniform(0, 2*np.pi, nsamples),
            'ra': np.random.uniform(0, 2*np.pi, nsamples),
            'dec': np.random.uniform(-np.pi/2, np.pi/2, nsamples),
            'psi': np.random.uniform(0, 2*np.pi, nsamples),
            'phase': np.random.uniform(0, 2*np.pi, nsamples),
        }
        
        if include_spins:
            params.update({
                'a_1': np.random.uniform(0, 0.8, nsamples),
                'a_2': np.random.uniform(0, 0.8, nsamples),
                'tilt_1': np.random.uniform(0, np.pi, nsamples),
                'tilt_2': np.random.uniform(0, np.pi, nsamples),
                'phi_12': np.random.uniform(0, 2*np.pi, nsamples),
                'phi_jl': np.random.uniform(0, 2*np.pi, nsamples),
            })
        
        return params
    
    def _validate_snr_output(self, snr_dict, expected_samples, test_name=""):
        """Validate SNR output format and numerical properties."""
        assert isinstance(snr_dict, dict), f"{test_name}: SNR output should be a dictionary"
        assert "optimal_snr_net" in snr_dict, f"{test_name}: Missing 'optimal_snr_net'"
        
        snr_arr = np.asarray(snr_dict["optimal_snr_net"])
        assert snr_arr.shape == (expected_samples,), f"{test_name}: Shape mismatch"
        assert np.all(np.isfinite(snr_arr)), f"{test_name}: Non-finite SNR values"
        assert np.all(np.isreal(snr_arr)), f"{test_name}: SNR values not real"
        assert np.all(snr_arr >= 0), f"{test_name}: Negative SNR values"
        assert snr_arr.dtype == np.float64, f"{test_name}: Wrong dtype"
    
    def _create_gwsnr(self, **overrides):
        """Create GWSNR instance with sensible defaults and optional overrides."""
        defaults = {
            'npool': 1,
            'sampling_frequency': 2048.0,
            'waveform_approximant': "IMRPhenomXPHM", 
            'frequency_domain_source_model': 'lal_binary_black_hole',
            'minimum_frequency': 20.0,
            'snr_type': "inner_product",
            'gwsnr_verbose': False,
            'multiprocessing_verbose': False,
        }
        defaults.update(overrides)
        return GWSNR(**defaults)

    def test_custom_psds(self):
        """
        Test SNR calculation with custom power spectral densities.
        
        Validates inner product method with design sensitivity PSDs and compares
        results with default PSDs to ensure custom noise curves work correctly.
        """
        custom_psds = {
            'L1': 'aLIGOaLIGODesignSensitivityT1800044',
            'H1': 'aLIGOaLIGODesignSensitivityT1800044', 
            'V1': 'AdvVirgo'
        }
        
        gwsnr_custom = self._create_gwsnr(
            psds=custom_psds,
        )
            
        nsamples = 3
        params = self._generate_bbh_params(nsamples, distance=400.0)
        
        # Test custom PSDs
        custom_snr = gwsnr_custom.snr(gw_param_dict=params)
        self._validate_snr_output(custom_snr, nsamples, "custom_psds")
        
        # Compare with default PSDs
        gwsnr_default = self._create_gwsnr(psds=None, ifos=["L1", "H1", "V1"])
        default_snr = gwsnr_default.snr(gw_param_dict=params)
        
        # Validate that custom PSDs produce reasonable results
        custom_arr = np.asarray(custom_snr["optimal_snr_net"])
        default_arr = np.asarray(default_snr["optimal_snr_net"])
        ratio = custom_arr / default_arr
        
        assert np.all(ratio > 0.1) and np.all(ratio < 10.0), \
            "Custom PSD SNRs should be within reasonable range of defaults"

In [3]:
TestGWSNRInnerProduct().test_custom_psds()


Initializing GWSNR class...

Trying to get the psd from pycbc:  aLIGOaLIGODesignSensitivityT1800044
Trying to get the psd from pycbc:  aLIGOaLIGODesignSensitivityT1800044
Trying to get the psd from pycbc:  AdvVirgo
Intel processor has trouble allocating memory when the data is huge. So, by default for IMRPhenomXPHM, duration_max = 64.0. Otherwise, set to some max value like duration_max = 600.0 (10 mins)


solving SNR with inner product


TypeError: 'PowerSpectralDensity' object is not subscriptable